on:
  repository_dispatch:
  #POST should have a -d '{"event_type":"on-demand-test"}'
    types: [on-demand-test]
jobs:
  lets-try-matrix:
    strategy:
      matrix:
        versions: [10, 12]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - run: echo "$RUNNER_OS"