on:
  #this will run test on the pull-req branch
  pull_request:
    types: [opened, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: run event
        run: echo "this is a label event"