on:
  repository_dispatch:
    types: [on-demand-test]
jobs:
  lets-try-matrix:
    strategy:
      matrix:
        versions: [10, 12]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - run: echo "$RUNNER_OS"