on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Chrckout repo
        uses: actions/checkout@v3
      - name: build docker-compose
        run: docker-compose up -d
      - name: archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            dist
            !dist/**/*.md
      - name: archive code production results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: output/test/code-coverage.html
